config/routes.rb
# frozen_string_literal: true

require 'sidekiq/web'
require 'sidekiq-scheduler/web'

if Rails.env.production?
  Sidekiq::Web.use Rack::Auth::Basic do |username, password|
    user_comp = ActiveSupport::SecurityUtils.secure_compare(
      ::Digest::SHA256.hexdigest(username),
      ::Digest::SHA256.hexdigest(ENV['SIDEKIQ_USERNAME'])
    )

    pass_comp = ActiveSupport::SecurityUtils.secure_compare(
      ::Digest::SHA256.hexdigest(password),
      ::Digest::SHA256.hexdigest(ENV['SIDEKIQ_PASSWORD'])
    )

    user_comp & pass_comp
  end
end

Rails.application.routes.draw do
  root 'home#index'
  mount RailsAdmin::Engine => '/rails_admin', as: 'rails_admin'
  mount Sidekiq::Web, at: '/sidekiq' if defined? Sidekiq::Web

  get '/for_organizations', to: 'home#for_organizations'
  get '/for_organizations/administration', to: 'home#administration', as: :administration
  get '/for_organizations/recruiting', to: 'home#recruiting', as: :recruiting
  get '/wieso-myzivi', to: 'home#for_civil_servants', as: :for_civil_servants
  get '/about_us', to: 'home#about_us'
  get '/zivi-faq', to: 'home#civil_servant_faq', as: :civil_servant_faq
  get '/agb', to: 'home#agb'
  get '/privacy_policy', to: 'home#privacy_policy'
  get '/pricing', to: 'home#pricing'
  resources :job_postings, param: :slug, only: %i[index show] do
    get 'widget', on: :member
  end
  resources :blog_entries, param: :slug, only: %i[index show], path: 'blog'

  devise_for :users, controllers: {
    invitations: 'users/invitations',
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }
  devise_for :sys_admins

  authenticated :sys_admin do
    namespace :sys_admins do
      resources :blog_entries, param: :slug
    end
  end

  resource :mailing_list, only: :create
  resources :expense_sheets, only: :show
  resources :service_inquiries, only: %i[new create]

  namespace :civil_servants do
    get '/', to: 'overview#index'

    resource :civil_servant, only: %i[edit update], on: :collection
    resources :service_agreements, only: :index do
      patch 'accept', to: 'service_agreements#accept'
      patch 'decline', to: 'service_agreements#decline'
    end
    resources :services, only: %i[index show]

    get 'register', to: 'registrations#edit'
    patch 'register', to: 'registrations#update'
  end

  namespace :organizations do
    get '/', to: 'overview#index'

    resource :organization, only: %i[edit update]
    resources :organization_members, as: 'members', except: :show
    resources :organization_holidays, except: :show
    resources :service_specifications, except: :show
    resources :service_agreements, only: %i[index destroy create new]
    get '/service_agreements/civil_servants/search',
        to: 'service_agreements#search', as: 'service_agreement_civil_servant_search'
    resources :payments, except: :edit
    resources :expense_sheets, except: :show
    get '/phone_list', to: 'phone_list#index', as: 'phone_list'
    get '/phone_list/:name', to: 'phone_list#index', as: 'named_phone_list'
    resources :services, only: :index
    resources :civil_servants, only: %i[index show] do
      resources :services, only: :show do
        put :confirm, on: :member
      end
    end
    resources :job_postings, only: %i[index edit update]
  end

  get '/401' => 'errors#unauthorized', as: :unauthorized
  get '/404' => 'errors#not_found', as: :not_found
  get '/500' => 'errors#internal_server_error', as: :internal_server_error
  get '/422' => 'errors#unprocessable_entity', as: :unprocessable_entity
  get '/robots', to: 'robots#robots'
  get '/sitemap.xml' => redirect(ENV['SITEMAP_PUBLIC_URL']) if ENV['SITEMAP_PUBLIC_URL'].present?
end

app/models/blog_entry.rb
# frozen_string_literal: true

class BlogEntry < ApplicationRecord
  SUPPORTED_TAGS = %w[article news podcast].freeze

  include Sluggable

  has_rich_text :content

  validates :author, :content, :title, :description, :slug, presence: true
  validates :tags, inclusion: { in: SUPPORTED_TAGS }

  scope :published, -> { where(published: true) }
  scope :including_tags, lambda { |*tags|
    merge(tags.map { |tag| BlogEntry.where('? = ANY(tags)', tag) }.reduce(&:or))
  }

  def default_slug
    title.parameterize
  end
end

app/models/sys_admin.rb
# frozen_string_literal: true

class SysAdmin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable,
         :rememberable,
         :validatable,
         :lockable,
         :trackable
end

app/controllers/blog_entries_controller.rb
# frozen_string_literal: true

class BlogEntriesController < ApplicationController
  include Pagy::Backend

  ITEMS = 20

  authorize_resource

  around_action do |_controller, action|
    I18n.with_locale(:'de-CH', &action)
  end

  def index
    @pagy, @blog_entries = pagy(
      BlogEntry.published.including_tags(*filter_params[:tags]).order(created_at: :desc),
      items: ITEMS
    )
  end

  def show
    @blog_entry = BlogEntry.find_by(slug: slug_params)
    raise ActiveRecord::RecordNotFound unless can?(:read, @blog_entry)
  end

  private

  def slug_params
    params.require(:slug)
  end

  # :reek:DuplicateMethodCall
  def filter_params
    filter = params.permit(filter: { tags: [] })[:filter] || {}
    filter[:tags] ||= BlogEntry::SUPPORTED_TAGS
    @filter_params = filter
  end
end

app/controllers/sys_admins/blog_entries_controller.rb
# frozen_string_literal: true

module SysAdmins
  class BlogEntriesController < ApplicationController
    layout 'sys_admins/application'

    before_action :set_blog_entry, only: %i[show edit update destroy]

    def index
      @blog_entries = BlogEntry.order(created_at: :desc)
    end

    def show; end

    def new
      @blog_entry = BlogEntry.new
    end

    def edit; end

    def create
      @blog_entry = BlogEntry.new(blog_entry_params)

      if @blog_entry.save
        redirect_to sys_admins_blog_entry_path(@blog_entry),
                    notice: I18n.t('sys_admins.blog_entries.successful_creation')
      else
        flash.now[:error] = I18n.t('sys_admins.blog_entries.erroneous_creation')
        render :new
      end
    end

    def update
      if @blog_entry.update(blog_entry_params)
        redirect_to sys_admins_blog_entry_path(@blog_entry),
                    notice: I18n.t('sys_admins.blog_entries.successful_update')
      else
        flash.now[:error] = I18n.t('sys_admins.blog_entries.erroneous_update')
        render :edit
      end
    end

    def destroy
      @blog_entry.destroy
      redirect_to sys_admins_blog_entries_path, notice: t('.successful_destroy')
    end

    private

    def set_blog_entry
      @blog_entry = BlogEntry.find_by!(slug: params[:slug])
    end

    def blog_entry_params
      params.require(:blog_entry)
            .permit(:title, :subtitle, :content,
                    :author, :published, :description,
                    :slug, :created_at, tags: []).tap do |entry_params|
        entry_params[:tags]&.reject!(&:blank?)
      end
    end
  end
end

app/helpers/blog_entries_helper.rb
# frozen_string_literal: true

module BlogEntriesHelper
  def tags_filter_menu_items(filter_params)
    menu_items = BlogEntry::SUPPORTED_TAGS.map do |blog_entry_tag|
      tag_selected = filter_params[:tags].include?(blog_entry_tag)
      link_to(filter_path(blog_entry_tag, filter_params, tag_selected), class: 'dropdown-item') do
        concat(
          tag.div(class: 'd-inline-block mr-2', style: 'width: 14px') do
            tag.i(class: 'fas fa-check mr-2') if tag_selected
          end
        )
        concat I18n.t(blog_entry_tag, scope: 'activerecord.arrays.blog_entry.tags')
      end
    end

    safe_join(menu_items)
  end

  private

  def filter_path(blog_entry_tag, filter_params, tag_selected)
    new_tags = tag_selected ? filter_params[:tags] - [blog_entry_tag] : filter_params[:tags] + [blog_entry_tag]
    params.permit(:controller, :action).merge({ filter: filter_params.merge(tags: new_tags.empty? ? [''] : new_tags) })
  end
end

app/views/sys_admins/blog_entries/_badge.html.slim
- if blog_entry.published?
  .badge.badge-success = t('activerecord.enums.blog_entry.published.true')
- else
  .badge.badge-secondary = t('activerecord.enums.blog_entry.published.false')

app/views/sys_admins/blog_entries/_form.html.slim
.card.card-body.mb-5
  = simple_form_for [:sys_admins, @blog_entry] do |f|
    = f.input :published
    .row
      .col-12.col-md-6
        = f.input :title, input_html: { autocomplete: 'off' }
      .col-12.col-md-6
        = f.input :subtitle, input_html: { autocomplete: 'off' }
      .col-12.col-md-6
        .row
          .col-12.col-xxl-6
            = f.input :author, input_html: { autocomplete: 'on' }
          .col-12.col-xxl-6
            = f.input :created_at
          .col-12
            = f.input :slug,
                    required: f.object.persisted?,
                    hint: (t('.slug_hint') if f.object.new_record?)
      .col-12.col-md-6
        = f.input :tags,
                collection: BlogEntry::SUPPORTED_TAGS.index_by { |tag| I18n.t(tag, scope: 'activerecord.arrays.blog_entry.tags') },
                include_blank: false,
                input_html: { multiple: true }
    = f.input :description
    .field
      = f.label :content
      = f.rich_text_area :content
    .actions.mt-2 = f.submit class: 'btn btn-primary'

app/views/sys_admins/blog_entries/edit.html.slim
.mt-3
  = link_to sys_admins_blog_entries_path do
    i.fas.fa-chevron-left.mr-2
    = t('actions.back')

h1.mt-3.mb-4 = t('.title')

= render 'form'

app/views/sys_admins/blog_entries/index.html.slim
h1.mt-3.mb-4 = t('.title')

.card.my-3
  .card-header
    .row.align-items-center.justify-content-between
      .col-4.col-sm-auto.d-flex.align-items-center.pr-0
        h4.fs-0.mb-0.text-nowrap.py-2.py-xl-0 = t('.table_title')
      .col-8.col-sm-auto.text-right.pl-2
        = button_to new_sys_admins_blog_entry_path, class: 'btn btn-falcon-default btn-sm', method: :get do
          i.fas.fa-plus data-fa-transform="shrink-3 down-2"
          span.d-none.d-sm-inline-block.ml-1 = t('.new')
  .card-body.p-0
    .falcon-data-table
      .dataTables_wrapper.dt-bootstrap4.no-footer
        .table-responsive
          table.table.table-sm.mb-0.table-striped.table-dashboard.fs--1.data-table.border-bottom.border-200.dataTable.no-footer role="grid"
            thead.bg-200.text-900
              tr role="row"
                th.align-middle = BlogEntry.human_attribute_name(:title)
                th.align-middle = BlogEntry.human_attribute_name(:author)
                th.align-middle = BlogEntry.human_attribute_name(:description)
                th.align-middle = BlogEntry.human_attribute_name(:tags)
                th.align-middle = BlogEntry.human_attribute_name(:published)
                th
            tbody#customers
              - if @blog_entries.empty?
                tr
                  td.text-center.border-bottom-0 colspan="5"
                    h5.mt-2 = t('.empty_table')
                    p = link_to(t('.new_blog_entry'), new_sys_admins_blog_entry_path)
              - @blog_entries.each do |blog_entry|
                tr role="row"
                  td.py-2.align-middle = link_to(blog_entry.title, sys_admins_blog_entry_path(blog_entry))
                  td.py-2.align-middle = blog_entry.author
                  td.py-2.align-middle = blog_entry.description.truncate(40)
                  td.py-2.align-middle
                    - blog_entry.tags.map do |tag|
                      .badge.badge-dark.mr-2 = t(tag, scope: 'activerecord.arrays.blog_entry.tags')
                  td.py-2.align-middle = render 'sys_admins/blog_entries/badge', blog_entry: blog_entry
                  td.py.align-middle.text-right.pr-4
                    = link_to edit_sys_admins_blog_entry_path(blog_entry), class: 'ml-2' do
                      i.fas.fa-pencil-alt
                    - unless blog_entry.published?
                      = link_to sys_admins_blog_entry_path(blog_entry, blog_entry: { published: true }),
                              method: :put,
                              'data-toggle': 'tooltip',
                              'data-placement': 'top',
                              title: t('.publish_tooltip'),
                              class: 'ml-2' do
                        i.fas.fa-cloud-upload-alt
                    = link_to sys_admins_blog_entry_path(blog_entry),
                            method: :delete,
                            class: 'ml-2 text-danger',
                            'data-confirm': t('.destroy_confirm') do
                      i.fas.fa-trash

app/views/sys_admins/blog_entries/new.html.slim
.mt-3
  = link_to sys_admins_blog_entries_path do
    i.fas.fa-chevron-left.mr-2
    = t('actions.back')

h1.mt-3.mb-4 = t('.title')

= render 'form'

app/views/sys_admins/blog_entries/show.html.slim
.mt-3
  = link_to sys_admins_blog_entries_path do
    i.fas.fa-chevron-left.mr-2
    = t('actions.back')

.d-flex.justify-content-between.align-items-baseline
  div: h1.mt-3 = @blog_entry.title
  div = render 'sys_admins/blog_entries/badge', blog_entry: @blog_entry
h2.h3.mb-3.text-muted = @blog_entry.subtitle
h5.text-muted #{@blog_entry.author} / #{l(@blog_entry.created_at)}
.mt-2
  - @blog_entry.tags.map do |tag|
    .badge.badge-light.mr-2 = t(tag, scope: 'activerecord.arrays.blog_entry.tags')
.card.mt-3
  .card-header
    .text-right
      = link_to @blog_entry, target: '_blank' do
        i.fas.fa-eye
      = link_to edit_sys_admins_blog_entry_path(@blog_entry), class: 'ml-2' do
        i.fas.fa-pencil-alt
      = link_to sys_admins_blog_entry_path(@blog_entry),
              method: :delete,
              class: 'ml-2 text-danger',
              'data-confirm': t('sys_admins.blog_entries.index.destroy_confirm') do
        i.fas.fa-trash
  .card-body.bg-light
    h5 = t('activerecord.attributes.blog_entry.description')
    = @blog_entry.description
    hr
    h5 = t('activerecord.attributes.blog_entry.content')
    == @blog_entry.content