config/routes.rb
# frozen_string_literal: true

require 'sidekiq/web'
require 'sidekiq-scheduler/web'

if Rails.env.production?
  Sidekiq::Web.use Rack::Auth::Basic do |username, password|
    user_comp = ActiveSupport::SecurityUtils.secure_compare(
      ::Digest::SHA256.hexdigest(username),
      ::Digest::SHA256.hexdigest(ENV['SIDEKIQ_USERNAME'])
    )

    pass_comp = ActiveSupport::SecurityUtils.secure_compare(
      ::Digest::SHA256.hexdigest(password),
      ::Digest::SHA256.hexdigest(ENV['SIDEKIQ_PASSWORD'])
    )

    user_comp & pass_comp
  end
end

Rails.application.routes.draw do
  root 'home#index'
  mount RailsAdmin::Engine => '/rails_admin', as: 'rails_admin'
  mount Sidekiq::Web, at: '/sidekiq' if defined? Sidekiq::Web

  get '/for_organizations', to: 'home#for_organizations'
  get '/for_organizations/administration', to: 'home#administration', as: :administration
  get '/for_organizations/recruiting', to: 'home#recruiting', as: :recruiting
  get '/wieso-myzivi', to: 'home#for_civil_servants', as: :for_civil_servants
  get '/about_us', to: 'home#about_us'
  get '/zivi-faq', to: 'home#civil_servant_faq', as: :civil_servant_faq
  get '/agb', to: 'home#agb'
  get '/privacy_policy', to: 'home#privacy_policy'
  get '/pricing', to: 'home#pricing'
  resources :job_postings, param: :slug, only: %i[index show] do
    get 'widget', on: :member
  end
  resources :blog_entries, param: :slug, only: %i[index show], path: 'blog'

  devise_for :users, controllers: {
    invitations: 'users/invitations',
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }
  devise_for :sys_admins

  authenticated :sys_admin do
    namespace :sys_admins do
      resources :blog_entries, param: :slug
    end
  end

  resource :mailing_list, only: :create
  resources :expense_sheets, only: :show
  resources :service_inquiries, only: %i[new create]

  namespace :civil_servants do
    get '/', to: 'overview#index'

    resource :civil_servant, only: %i[edit update], on: :collection
    resources :service_agreements, only: :index do
      patch 'accept', to: 'service_agreements#accept'
      patch 'decline', to: 'service_agreements#decline'
    end
    resources :services, only: %i[index show]

    get 'register', to: 'registrations#edit'
    patch 'register', to: 'registrations#update'
  end

  namespace :organizations do
    get '/', to: 'overview#index'

    resource :organization, only: %i[edit update]
    resources :organization_members, as: 'members', except: :show
    resources :organization_holidays, except: :show
    resources :service_specifications, except: :show
    resources :service_agreements, only: %i[index destroy create new]
    get '/service_agreements/civil_servants/search',
        to: 'service_agreements#search', as: 'service_agreement_civil_servant_search'
    resources :payments, except: :edit
    resources :expense_sheets, except: :show
    get '/phone_list', to: 'phone_list#index', as: 'phone_list'
    get '/phone_list/:name', to: 'phone_list#index', as: 'named_phone_list'
    resources :services, only: :index
    resources :civil_servants, only: %i[index show] do
      resources :services, only: :show do
        put :confirm, on: :member
      end
    end
    resources :job_postings, only: %i[index edit update]
  end

  get '/401' => 'errors#unauthorized', as: :unauthorized
  get '/404' => 'errors#not_found', as: :not_found
  get '/500' => 'errors#internal_server_error', as: :internal_server_error
  get '/422' => 'errors#unprocessable_entity', as: :unprocessable_entity
  get '/robots', to: 'robots#robots'
  get '/sitemap.xml' => redirect(ENV['SITEMAP_PUBLIC_URL']) if ENV['SITEMAP_PUBLIC_URL'].present?
end

app/controllers/organizations/base_controller.rb
# frozen_string_literal: true

module Organizations
  class BaseController < ApplicationController
    include ::AuthenticableAndAuthorizable

    before_action -> { authorize! :access, :organization_portal }

    layout 'organizations/application'
  end
end

app/controllers/organizations/civil_servants_controller.rb
# frozen_string_literal: true

module Organizations
  class CivilServantsController < BaseController
    load_and_authorize_resource
    breadcrumb 'organizations.civil_servants.index', :organizations_civil_servants_path

    def index
      load_filters
      @civil_servants = filtered_civil_servants
    end

    def show
      breadcrumb @civil_servant.full_name, organizations_civil_servants_path(@civil_servant)
      load_filters
      @services = Service
                  .accessible_by(current_ability)
                  .definitive
                  .where(civil_servant_id: @civil_servant.id)
                  .includes(:service_specification)
    end

    private

    def filtered_civil_servants
      service_filter = @filters[:show_inactive] ? {} : { services: Service.active }

      CivilServant
        .accessible_by(current_ability)
        .eager_load(:services)
        .where(service_filter)
        .distinct
        .includes(services: :service_specification)
        .order('"services"."beginning" DESC')
    end

    def load_filters
      @filters = {
        show_inactive: params.dig(:filters, :show_inactive) == 'true'
      }
    end
  end
end

app/controllers/organizations/expense_sheets_controller.rb
# frozen_string_literal: true

module Organizations
  class ExpenseSheetsController < BaseController
    PERMITTED_PARAMS = %i[
      duration work_days
      workfree_days sick_days
      unpaid_company_holiday_days paid_company_holiday_days
      paid_vacation_days paid_vacation_comment
      unpaid_vacation_days unpaid_vacation_comment
      clothing_expenses clothing_expenses_comment
      driving_expenses driving_expenses_comment
      extraordinary_expenses extraordinary_expenses_comment
    ].freeze

    load_and_authorize_resource
    breadcrumb 'organizations.expense_sheets.index', :organizations_expense_sheets_path

    before_action :edit_breadcrumbs, only: %i[edit update]

    def index
      load_filters
      @expense_sheets = filtered_expense_sheets.order(ending: :desc, beginning: :desc)
    end

    def edit
      load_suggestions
    end

    def update
      if @expense_sheet.update(expense_sheets_params)
        redirect_to edit_organizations_expense_sheet_path, notice: t('.successful_update')
      else
        load_suggestions
        flash.now[:error] = t('.erroneous_update')
        render :edit, status: :unprocessable_entity
      end
    end

    private

    def load_suggestions
      @suggestions = ExpenseSheetCalculators::SuggestionsCalculator.new(@expense_sheet).suggestions
    end

    def expense_sheets_params
      params.require(:expense_sheet).permit(*PERMITTED_PARAMS)
    end

    def filtered_expense_sheets
      @expense_sheets = @expense_sheets.includes(:civil_servant)

      return @expense_sheets if @filters[:show_all]

      @expense_sheets.editable
    end

    def load_filters
      @filters = {
        show_all: params.dig(:filters, :show_all) == 'true'
      }
    end

    def edit_breadcrumbs
      breadcrumb @expense_sheet.civil_servant.full_name, organizations_expense_sheets_path(@expense_sheet)
    end
  end
end

app/controllers/organizations/job_postings_controller.rb
# frozen_string_literal: true

module Organizations
  class JobPostingsController < BaseController
    include Pagy::Backend

    ITEMS = 10

    load_and_authorize_resource find_by: :slug
    skip_authorize_resource only: :index
    breadcrumb 'organizations.job_postings.index', :organizations_job_postings_path

    before_action :edit_breadcrumb, only: %i[edit update]

    def index
      @pagy, @job_postings = pagy(
        @job_postings.accessible_by(current_ability, :edit).order(:title),
        items: ITEMS
      )
    end

    def edit; end

    def update
      if @job_posting.update(job_posting_params)
        redirect_to edit_organizations_job_posting_path(@job_posting), notice: t('.successful_update')
      else
        flash.now[:error] = t('.erroneous_update')
        render :edit, status: :unprocessable_entity
      end
    end

    private

    def edit_breadcrumb
      breadcrumb @job_posting.title, organizations_job_postings_path(@job_posting)
    end

    def job_posting_params
      params.require(:job_posting).permit(
        :title, :description, :required_skills, :preferred, :category,
        :published, :preferred_skills, :priority_program, :language,
        :identification_number, :sub_category, :canton,
        :brief_description, :minimum_service_months, :weekly_work_time,
        :fixed_work_time, :good_reputation, :e_government, :work_on_weekend,
        :work_night_shift, :accommodation_provided, :food_provided
      )
    end
  end
end

app/controllers/organizations/organization_holidays_controller.rb
# frozen_string_literal: true

module Organizations
  class OrganizationHolidaysController < BaseController
    load_and_authorize_resource
    breadcrumb 'organizations.organizations.index', :edit_organizations_organization
    breadcrumb 'organizations.organization_holidays.index', :organizations_organization_holidays_path

    before_action :new_breadcrumb, only: %i[new create]
    before_action :edit_breadcrumb, only: %i[edit update]

    def index
      @organization_holidays = @organization_holidays.order(beginning: :desc)
    end

    def new; end

    def edit; end

    def create
      build_organization_holiday

      if @organization_holiday.save
        flash[:success] = t('organizations.organization_holidays.update.successful_create')
        redirect_to organizations_organization_holidays_path
      else
        flash.now[:error] = t('organizations.organization_holidays.update.erroneous_create')
        render :new, status: :unprocessable_entity
      end
    end

    def update
      if @organization_holiday.update(organization_holiday_params)
        flash[:success] = t('organizations.organization_holidays.update.successful_update')
        redirect_to organizations_organization_holidays_path
      else
        flash.now[:error] = t('organizations.organization_holidays.update.erroneous_update')
        render :edit, status: :unprocessable_entity
      end
    end

    def destroy
      if @organization_holiday.destroy
        flash[:success] = t('organizations.organization_holidays.update.successful_destroy')
        redirect_to organizations_organization_holidays_path
      else
        flash.now[:error] = t('organizations.organization_holidays.update.erroneous_destroy')
        render :edit, status: :unprocessable_entity
      end
    end

    private

    def organization_holiday_params
      params.require(:organization_holiday).permit(:description, :beginning, :ending)
    end

    def build_organization_holiday
      @organization_holiday = current_organization_admin
                              .organization
                              .organization_holidays
                              .build(organization_holiday_params)
    end

    def new_breadcrumb
      breadcrumb 'organizations.organization_holidays.new', :new_organizations_organization_holiday_path
    end

    def edit_breadcrumb
      breadcrumb @organization_holiday.description, :organizations_organization_holiday_path
    end
  end
end

app/controllers/organizations/organization_members_controller.rb
# frozen_string_literal: true

module Organizations
  class OrganizationMembersController < BaseController
    PERMITTED_ORGANIZATION_MEMBER_PARAMS = %i[first_name last_name phone organization_role email].freeze

    load_and_authorize_resource
    before_action :set_breadcrumb
    before_action :new_breadcrumbs, only: %i[new create]
    before_action :edit_breadcrumbs, only: %i[edit update]

    def index
      @organization_members = @organization_members.includes(:user)
    end

    def new; end

    def create
      if @organization_member.save
        flash[:success] = t('.successfully_created')
        redirect_to organizations_members_path
      else
        flash.now[:error] = t('.erroneous_create')
        render :new, status: :unprocessable_entity
      end
    end

    def edit; end

    def update
      if @organization_member.update(update_params)
        flash[:success] = t('.successfully_updated')
        redirect_to edit_organizations_member_path(@organization_member)
      else
        flash.now[:error] = t('.erroneous_update')
        render :edit, status: :unprocessable_entity
      end
    end

    def destroy
      if @organization_member != current_organization_admin && @organization_member.destroy
        flash[:success] = t('.successfully_deleted')
        redirect_to organizations_members_path
      else
        flash.now[:error] = t('.erroneous_delete')
        render :edit, status: :unprocessable_entity
      end
    end

    private

    def set_breadcrumb
      return if @organization_member == current_organization_admin

      breadcrumb 'organizations.organization_members.index',
                 organizations_members_path
    end

    def edit_breadcrumbs
      if @organization_member == current_organization_admin
        breadcrumb 'organizations.organization_members.profile', edit_organizations_member_path(@organization_member)
      else
        breadcrumb @organization_member.full_name, edit_organizations_member_path(@organization_member)
      end
    end

    def new_breadcrumbs
      breadcrumb 'organizations.organization_members.new', :new_organizations_member_path
    end

    def create_params
      params.require(:organization_member).permit(*PERMITTED_ORGANIZATION_MEMBER_PARAMS)
    end

    def update_params
      params.require(:organization_member).permit(*PERMITTED_ORGANIZATION_MEMBER_PARAMS, user_attributes: %i[email id])
    end
  end
end

app/controllers/organizations/overview_controller.rb
# frozen_string_literal: true

module Organizations
  class OverviewController < BaseController
    before_action -> { authorize! :read, :organization_overview }
    breadcrumb 'organizations.overview.index', :organizations_path

    def index
      @services = can?(:read, Service) ? load_services : Service.none
    end

    private

    def load_services
      Service.accessible_by(current_ability)
             .where(civil_servant_decided_at: nil)
             .or(Service.accessible_by(current_ability).where(confirmation_date: nil, civil_servant_agreed: true))
             .includes(:civil_servant, :service_specification)
             .order(civil_servant_agreed: :desc, confirmation_date: :desc, beginning: :asc)
    end
  end
end

app/helpers/organizations/organization_members_helper.rb
# frozen_string_literal: true

module Organizations
  module OrganizationMembersHelper
    def initials(organization_member)
      (organization_member.first_name.first + organization_member.last_name.first).upcase
    end
  end
end

app/helpers/organizations/overview_helper.rb
# frozen_string_literal: true

module Organizations
  module OverviewHelper
    def current_week_phone_list_path
      organizations_phone_list_path(format: :pdf,
                                    params: { filters: {
                                      beginning: Time.zone.today.beginning_of_week,
                                      ending: Time.zone.today.at_end_of_week
                                    } })
    end

    def current_month_phone_list_path
      organizations_phone_list_path(format: :pdf,
                                    params: { filters: {
                                      beginning: Time.zone.today.beginning_of_month,
                                      ending: Time.zone.today.at_end_of_month
                                    } })
    end

    def active_civil_servants_count
      current_organization.services.active.count
    end

    def editable_expense_sheets_count
      current_organization.expense_sheets.editable.count
    end

    # @param [Service] service
    def service_state_label(service)
      civil_servant_agreed = service.civil_servant_agreed?

      {
        (civil_servant_agreed && service.confirmation_date.present?) => I18n.t('service_states.active'),
        (civil_servant_agreed && service.confirmation_date.nil?) => I18n.t('service_states.pending_contract'),
        service.civil_servant_decided_at.nil? => I18n.t('service_states.waiting_for_civil_servant_decision'),
        (service.civil_servant_decided_at.present? && !civil_servant_agreed) =>
          I18n.t('service_states.civil_servant_rejected')
      }.fetch(true, nil)
    end
  end
end

app/helpers/organizations/payments_helper.rb
# frozen_string_literal: true

module Organizations
  module PaymentsHelper
    def payment_badge(payment)
      render "organizations/payments/badges/#{payment.state}"
    end

    # rubocop:disable Rails/OutputSafety
    def expense_sheet_collection_value(expense_sheet)
      <<~LABEL.squish.html_safe
        <strong>#{sanitize(expense_sheet.civil_servant.full_name, tags: [])}</strong>
        (#{l(expense_sheet.beginning)} - #{l(expense_sheet.ending)}, #{number_to_currency(expense_sheet.amount)})
      LABEL
    end
    # rubocop:enable Rails/OutputSafety
  end
end

app/helpers/organizations/phone_list_helper.rb
# frozen_string_literal: true

module Organizations
  module PhoneListHelper
    def phone_list_pdf_link(filters, &block)
      link_to(pdf_url(filters), target: '_blank', rel: 'noopener', class: 'btn btn-falcon-default btn-sm', &block)
    end

    private

    def pdf_url(filters)
      {
        format: 'pdf',
        name: t('pdfs.phone_list.file_name', today: l(Time.zone.today)).parameterize,
        params: pdf_url_params(filters[:beginning], filters[:ending])
      }
    end

    def pdf_url_params(beginning, ending)
      return {} if beginning.nil? || ending.nil?

      { filters: { beginning: beginning, ending: ending } }
    end
  end
end

app/views/organizations/payments/_payment_row.html.slim
tr.btn-reveal-trigger.odd role="row"
  td.py-2.align-middle
    = link_to t('.expense_sheets', count: payment.expense_sheets.size), organizations_payment_path(payment)
  td.py-2.align-middle = l(payment.created_at.to_date)
  td.py-2.align-middle = number_to_currency(payment.amount, locale: 'de-CH')
  td.py-2.align-middle
    .d-inline-flex
      = payment_badge(payment)
  td.py-2.align-middle
    .dropdown.text-sans-serif
      button.btn.btn-link.text-600.btn-sm.dropdown-toggle.btn-reveal.mr-3 aria-expanded="false" aria-haspopup="true" data-boundary="viewport" data-toggle="dropdown" type="button"
        i.fas.fa-ellipsis-h.fs--1
      .dropdown-menu.dropdown-menu-right.border.py-0 aria-labelledby="order-dropdown-0"
        .bg-white.py-2
          = link_to organizations_payment_path(payment), class: 'dropdown-item' do
            i.fas.fa-eye.mr-1
            = t('.details')
          = link_to organizations_payment_path(payment, format: :xml), class: 'dropdown-item' do
            i.fas.fa-download.mr-1
            = t('.download_pain')
          - if payment.open?
            = link_to organizations_payment_path(payment, payment: { state: 'paid' }), class: 'dropdown-item', method: :put do
              i.fas.fa-check.mr-1
              = t('.mark_as_paid')
            .dropdown-divider
            = link_to organizations_payment_path(payment),
                    class: 'dropdown-item text-danger',
                    method: :delete,
                    data: { confirm: 'Really?' } do
              i.fas.fa-trash-alt.mr-1
              = t('.delete')

app/views/organizations/payments/index.html.slim
.card.mb-3.mb-lg-0
  .card-header.bg-light.d-flex.justify-content-between.align-items-center
    h5 = t('.title')
    = link_to t('.new_payment'), new_organizations_payment_path, class: 'btn btn-primary'
  .card-body.p-0
    .falcon-data-table
      .dataTables_wrapper.dt-bootstrap4.no-footer
        .row.mx-1
          .col-sm-12.col-md-6
          .col-sm-12.col-md-6
        .table-responsive
          table.table.table-sm.mb-0.table-striped.table-dashboard.fs--1.data-table.border-bottom.border-200.dataTable.no-footer role="grid"
            thead.bg-200.text-900
              tr role="row"
                th.align-middle = t('.table_headers.payment')
                th.align-middle = t('.table_headers.date')
                th.align-middle = t('.table_headers.amount')
                th.align-middle = t('.table_headers.status')
                th.align-middle = t('.table_headers.actions')
            tbody
              = render partial: 'organizations/payments/payment_row', collection: @payments, as: :payment
        / TODO: Implement pagination
        / .row.no-gutters.px-1.py-3.align-items-center.justify-content-center
          .col-auto
            #DataTables_Table_0_paginate.dataTables_paginate.paging_simple_numbers
              ul.pagination.pagination-sm
                li#DataTables_Table_0_previous.paginate_button.page-item.previous.disabled
                  a.page-link aria-controls="DataTables_Table_0" data-dt-idx="0" href="#" tabindex="0"
                    i.fas.fa-chevron-left
                li.paginate_button.page-item.active
                  a.page-link aria-controls="DataTables_Table_0" data-dt-idx="1" href="#" tabindex="0" 1
                li.paginate_button.page-item
                  a.page-link aria-controls="DataTables_Table_0" data-dt-idx="2" href="#" tabindex="0" 2
                li.paginate_button.page-item
                  a.page-link aria-controls="DataTables_Table_0" data-dt-idx="3" href="#" tabindex="0" 3
                li#DataTables_Table_0_next.paginate_button.page-item.next
                  a.page-link aria-controls="DataTables_Table_0" data-dt-idx="4" href="#" tabindex="0"
                    i.fas.fa-chevron-right

app/views/organizations/payments/new.html.slim
.card.mb-3
  .bg-holder.d-none.d-lg-block.bg-card.corner-background-warning
  .card-body: h3.my-0 = t('.title')
.card.mt-3
  .card-body.bg-light
    = simple_form_for([:organizations, @payment]) do |f|
      = f.association :expense_sheets,
              collection: @accessible_expense_sheets,
              as: :check_boxes,
              label_method: method(:expense_sheet_collection_value)
      = f.submit t('.submit'), class: 'btn btn-primary'

app/views/organizations/payments/show.html.slim
.card.mb-3
  .bg-holder.d-none.d-lg-block.bg-card.corner-background-success
  .card-body
    .row
      .col-lg-8
        .d-flex.align-items-center
          h3.my-0 = t('.title', date: l(@payment.created_at.to_date))
          .ml-2 = payment_badge(@payment)
        h4.text-muted = number_to_currency(@payment.amount, locale: 'de-CH')
        .d-flex.mt-4.mb-0
          - if current_organization.pain_generation_enabled?
            = link_to(organizations_payment_path(@payment, format: :xml), class: 'btn btn-falcon-default btn-sm')
              i.fas.fa-download.mr-1
              = t('organizations.payments.payment_row.download_pain')
          - else
            div[
              data-toggle='popover'
              data-sanitize='false'
              data-content=t('.disabled_pain_button_html', link: edit_organizations_organization_path)
              data-trigger='hover'
              data-html='true'
              data-delay='{ "show": 0, "hide": 3000 }'
              data-custom-class='shadow-popover'
            ]
              button.btn.btn-falcon-default.btn-sm.disabled style='pointer-events: none'
                i.fas.fa-download.mr-1
                = t('organizations.payments.payment_row.download_pain')
          - if @payment.open?
            .dropdown
              button#dropdown-button.btn.btn-falcon-default.btn-sm.dropdown-toggle.ml-2.dropdown-caret-none aria-expanded="false" aria-haspopup="true" data-toggle="dropdown" type="button"
                i.fas.fa-ellipsis-h
              .dropdown-menu aria-labelledby="dropdown-button"
                = link_to(organizations_payment_path(@payment, payment: { state: 'paid' }), method: :put, class: 'dropdown-item') do
                  i.fas.fa-check.mr-1
                  = t('organizations.payments.payment_row.mark_as_paid')
                .dropdown-divider
                = link_to organizations_payment_path(@payment),
                        class: 'dropdown-item text-danger',
                        method: :delete,
                        data: { confirm: 'Really?' } do
                  i.fas.fa-trash-alt.mr-1
                  = t('organizations.payments.payment_row.delete')
.card.mt-3
  .card-header.bg-white
    .row.align-items-center
      .col
        h5.mb-0
          = t('.expense_sheets_table.title')
          span.d-none.d-sm-inline-block.ml-1.text-muted = "(#{@payment.expense_sheets.count})"
  .card-body.p-0.bg-light
    = render ExpenseSheetsTableComponent.new(expense_sheets: @payment.expense_sheets)