config/routes.rb
# frozen_string_literal: true

require 'sidekiq/web'
require 'sidekiq-scheduler/web'

if Rails.env.production?
  Sidekiq::Web.use Rack::Auth::Basic do |username, password|
    user_comp = ActiveSupport::SecurityUtils.secure_compare(
      ::Digest::SHA256.hexdigest(username),
      ::Digest::SHA256.hexdigest(ENV['SIDEKIQ_USERNAME'])
    )

    pass_comp = ActiveSupport::SecurityUtils.secure_compare(
      ::Digest::SHA256.hexdigest(password),
      ::Digest::SHA256.hexdigest(ENV['SIDEKIQ_PASSWORD'])
    )

    user_comp & pass_comp
  end
end

Rails.application.routes.draw do
  root 'home#index'
  mount RailsAdmin::Engine => '/rails_admin', as: 'rails_admin'
  mount Sidekiq::Web, at: '/sidekiq' if defined? Sidekiq::Web

  get '/for_organizations', to: 'home#for_organizations'
  get '/for_organizations/administration', to: 'home#administration', as: :administration
  get '/for_organizations/recruiting', to: 'home#recruiting', as: :recruiting
  get '/wieso-myzivi', to: 'home#for_civil_servants', as: :for_civil_servants
  get '/about_us', to: 'home#about_us'
  get '/zivi-faq', to: 'home#civil_servant_faq', as: :civil_servant_faq
  get '/agb', to: 'home#agb'
  get '/privacy_policy', to: 'home#privacy_policy'
  get '/pricing', to: 'home#pricing'
  resources :job_postings, param: :slug, only: %i[index show] do
    get 'widget', on: :member
  end
  resources :blog_entries, param: :slug, only: %i[index show], path: 'blog'

  devise_for :users, controllers: {
    invitations: 'users/invitations',
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }
  devise_for :sys_admins

  authenticated :sys_admin do
    namespace :sys_admins do
      resources :blog_entries, param: :slug
    end
  end

  resource :mailing_list, only: :create
  resources :expense_sheets, only: :show
  resources :service_inquiries, only: %i[new create]

  namespace :civil_servants do
    get '/', to: 'overview#index'

    resource :civil_servant, only: %i[edit update], on: :collection
    resources :service_agreements, only: :index do
      patch 'accept', to: 'service_agreements#accept'
      patch 'decline', to: 'service_agreements#decline'
    end
    resources :services, only: %i[index show]

    get 'register', to: 'registrations#edit'
    patch 'register', to: 'registrations#update'
  end

  namespace :organizations do
    get '/', to: 'overview#index'

    resource :organization, only: %i[edit update]
    resources :organization_members, as: 'members', except: :show
    resources :organization_holidays, except: :show
    resources :service_specifications, except: :show
    resources :service_agreements, only: %i[index destroy create new]
    get '/service_agreements/civil_servants/search',
        to: 'service_agreements#search', as: 'service_agreement_civil_servant_search'
    resources :payments, except: :edit
    resources :expense_sheets, except: :show
    get '/phone_list', to: 'phone_list#index', as: 'phone_list'
    get '/phone_list/:name', to: 'phone_list#index', as: 'named_phone_list'
    resources :services, only: :index
    resources :civil_servants, only: %i[index show] do
      resources :services, only: :show do
        put :confirm, on: :member
      end
    end
    resources :job_postings, only: %i[index edit update]
  end

  get '/401' => 'errors#unauthorized', as: :unauthorized
  get '/404' => 'errors#not_found', as: :not_found
  get '/500' => 'errors#internal_server_error', as: :internal_server_error
  get '/422' => 'errors#unprocessable_entity', as: :unprocessable_entity
  get '/robots', to: 'robots#robots'
  get '/sitemap.xml' => redirect(ENV['SITEMAP_PUBLIC_URL']) if ENV['SITEMAP_PUBLIC_URL'].present?
end

app/controllers/home_controller.rb
# frozen_string_literal: true

class HomeController < ApplicationController
  before_action -> { I18n.locale = :'de-CH' }

  content_security_policy false

  def index; end

  def for_organizations; end

  def for_civil_servants; end

  def administration; end

  def recruiting; end

  def civil_servant_faq
    @faqs = Faq.all
  end

  def agb; end

  def privacy_policy; end

  def about_us; end

  def pricing; end
end

app/views/home/_faq.de.html.slim
#faqAccordion.accordion
  = render CardAccordionEntryComponent.new(title: 'Was ist eigentlich MyZivi?', parent_id: 'faqAccordion', expanded: true) do
    p
      | MyZivi ist ein digitales Tool, gehostet in der Cloud, dass Dich in zwei Themen unterstützt;
        Rekrutierung und Administration von Zivis.
        Mit “MyZivi Recruiting” erstellst erstellst Du interessante Einsatzprofile,
        rekrutierst Zivis mit einem ausgeklügelten Kanban-Recruiting System und behältst stets die Übersicht,
        wenns um Deine Zivi Bewerbungen geht.
        Mit “MyZivi Admin” erstellst Du nach einer erfolgreichen Zivi-Rekrutierung digitale Einsatzvereinbarungen.
        Darüber hinaus kannst Du Deine Einsatzplanung vornehmen,
        Spesen automatisch auszahlen und mit Deinen Kollegen gemeinsam Zivis verwalten.
  = render CardAccordionEntryComponent.new(title: 'Wie funktioniert MyZivi?', parent_id: 'faqAccordion') do
    p
      | MyZivi kann mit jedem Browser (Google Chrome, Firefox, Safari, Opera, Edge etc.) benutzt werden.
        Du kannst MyZivi sogar mit Deinem Mobiltelefon bedienen.
        Solange Du eine Internetverbindung hast, kannst Du überall auf der Welt auf MyZivi zugreifen.
  = render CardAccordionEntryComponent.new(title: 'Wer steht hinter MyZivi?', parent_id: 'faqAccordion') do
    p
      | Wir sind drei Winterthurer Jungunternehmer mit Erfahrung im Verkauf,
        Entwicklung, Marketing und dem Zivildienst.
      =< link_to 'Hier kannst Du mehr über uns erfahren.', about_us_path
  = render CardAccordionEntryComponent.new( \
      title: 'Wie stehen MyZivi und das Bundesamt für Zivildienst zueinander?',
      parent_id: 'faqAccordion') do
    p
      | MyZivi ist ein unabhängiges Unternehmen und weder ein Teil von e-ZIVI noch vom Bundesamt für Zivildienst.
        Wir bieten Dir ein externes Tool an, dass Dich in Administration und Rekrutierung von Zivis unterstützt.
  = render CardAccordionEntryComponent.new(title: 'Was kostet MyZivi?', parent_id: 'faqAccordion') do
    p
      | Die Preise richten sich nach Anzahl Zivis, die zeitgleich bei Dir im Einsatz sind.
        Grundsätzlich zahlst Du 10 CHF / Monat pro Zivi.
        Sobald Du mehr als 5 Zivis zeitgleich im Einsatz hast, gibts einen Rabatt.
      =< link_to('Vereinbare einen kurzen Beratungstermin mit uns, um mehr zu erfahren.',
              Rails.configuration.x.urls.demo_url)
  = render CardAccordionEntryComponent.new(title: 'Wie kann ich mit MyZivi starten?', parent_id: 'faqAccordion') do
    p
      => link_to('Vereinbare einen kurzen Beratungstermin', Rails.configuration.x.urls.demo_url)
      | mit uns und wir führen Dich durch eine kurze Demo.
        Falls MyZivi das richtige für Deinen Betrieb ist, senden wir Dir einen Vertrag zu.
        Sobald Du uns diesen unterschrieben digital zurücksendest,
        dauert es 24 Stunden bis Dein MyZivi-Konto bereit steht.
  = render CardAccordionEntryComponent.new(title: 'Was sind die Vorteile von MyZivi?', parent_id: 'faqAccordion') do
    p
      | Mit MyZivi ersparst Du bis zu 8 Stunden administrative Arbeit pro Monat.
        Du schonst die Natur durch die komplette Digitalisierung Deiner Zivi-Prozesse.
        Desweiteren hast Du alle wichtigen Dokumente an einem Ort, jederzeit abrufbar.
        Dazu kannst Du nun Zivis aus einem erweiterten Pool rekrutieren und neue Zivis für Deinen Betrieb begeistern.
  = render CardAccordionEntryComponent.new(title: 'Was, wenn ich nach kurzer Zeit MyZivi nicht mehr verwenden will?',
          parent_id: 'faqAccordion') do
    p
      | Du verwendest MyZivi stets in einem Abo, das Du jederzeit kündigen kannst.
        Sobald Du eine Kündigung per Mail vornimmst, läuft Dein MyZivi-Konto noch bis Ende des Monats.
        Deine Daten stellen wir Dir in Ordnerstruktur zur Verfügung.
        Weitere Infos hierzu kannst Du unseren #{link_to('AGB', agb_path)} entnehmen.

app/views/home/_footer.de.html.slim
section.contact
  .container
    .text-center.text-white
      .h3.text-white Hast Du noch Fragen zu MyZivi?
      p Schreib uns eine kurze Nachricht und wir melden uns gerne bei Dir innerhalb von 24 Stunden
      = mail_to 'info@myzivi.ch', 'Anfrage senden', subject: 'Anfrage zu MyZivi', class: 'btn btn-secondary'
footer
  .container
    .mb-1 Folge MyZivi
    .d-inline-flex.order-0.order-md-1.mb-4.social-links
      a[
        href='https://instagram.com/myzivi.ch?utm_medium=copy_link'
        rel='noreferrer nofollow noopener'
        target='_blank'
      ]
        i.fab.fa-instagram.mr-2
        | Instagram
      a[
        href='https://www.linkedin.com/company/myzivi'
        rel='noreferrer nofollow noopener'
        target='_blank'
      ]
        i.fab.fa-linkedin.mr-2
        | LinkedIn
      a[
        href='https://www.facebook.com/MyZivich-111367494466350'
        rel='noreferrer nofollow noopener'
        target='_blank'
      ]
        i.fab.fa-facebook.mr-2
        | Facebook
      a[
        href='https://twitter.com/ZiviMy'
        rel='noreferrer nofollow noopener'
        target='_blank'
      ]
        i.fab.fa-twitter.mr-2
        | Twitter
    .d-flex.justify-content-between.flex-column.flex-md-row
      .copyright.mt-3.mt-md-0.order-1.order-md-0 © #{Time.zone.now.year} MyZivi KiG. Alle Rechte vorbehalten.
      .d-inline-flex.order-0.order-md-1
        = link_to('Login', new_user_session_path, class: 'text-muted')
        .mx-1 |
        = link_to('Preise', pricing_path, class: 'text-muted')
        .mx-1 |
        = link_to('Datenschutzerklärung', privacy_policy_path, class: 'text-muted')
        .mx-1 |
        = link_to('AGB', agb_path, class: 'text-muted')

app/views/home/_navbar.html.slim
nav.navbar.navbar-expand-lg.navbar-light.bg-light.my-zivi-top-navbar
  .container.py-2
    = link_to root_path, class: 'navbar-brand' do
      = image_pack_tag 'logo.svg', class: 'd-inline-block my-zivi-logo', height: 35
    button.navbar-toggler[
      aria-controls="navbarScroll"
      aria-expanded="false"
      aria-label="Toggle navigation"
      data-target="#navbarScroll"
      data-toggle="collapse"
      type="button"
    ]
      span.navbar-toggler-icon
        i.fas.fa-bars.fa-lg
    #navbarScroll.collapse.navbar-collapse
      ul.navbar-nav.mr-auto.my-2.my-lg-0.navbar-nav-scroll
        = navbar_link(t('home.navbar.links.job_postings'), job_postings_path)
        = dropdown_navbar_link(t('home.navbar.links.organizations'), for_organizations_path,
                dropdown_item(t('home.navbar.links.overview'), for_organizations_path),
                dropdown_item(t('home.navbar.links.admin'), administration_path),
                dropdown_item(t('home.navbar.links.recruiting'), recruiting_path),
                dropdown_item(t('home.navbar.links.pricing'), pricing_path))
        = navbar_link(t('home.navbar.links.about_us'), about_us_path)
        = navbar_link(t('home.navbar.links.blog'), blog_entries_path)
        = navbar_link(t('home.navbar.links.civil_servant_faq'), civil_servant_faq_path)
      .d-flex.mt-4.mt-lg-0
        - if content_for?(:displays_demo_button)
          = link_to t('home.navbar.demo'),
                  Rails.configuration.x.urls.demo_url,
                  class: 'btn btn-gradient',
                  target: '_blank',
                  rel: 'nofollow noopener noreferrer'
        - if content_for?(:displays_signup_button)
          = link_to t('home.navbar.signup'),
                  Rails.configuration.x.urls.civil_servant_register_form,
                  class: 'btn btn-gradient',
                  target: '_blank',
                  rel: 'nofollow noopener noreferrer'
.navbar-spacer

app/views/home/for_organizations.html.slim
- content_for(:container_class, 'index-container')
- content_for(:page_title, 'Für Betriebe')
- content_for(:page_description, 'Unsere Lösungen für Betriebe')
- content_for(:displays_demo_button, true)
= render 'home/navbar'

section.solution
  .container
    h3.section-title Unsere Lösungen für Betriebe
    p.section-subtitle
      | MyZivi deckt den gesamten Prozess ab:
        Zivis finden, Bewerbungsgespräche führen, Probetage durchführen,
        einstellen, einplanen und Spesenauszahlungen vornehmen
    .row.mt-5
      .col-12.col-md-6.text-center.text-xl-right
        = vite_image_tag 'home/illustrations/recruit.svg', class: 'illustration-image', alt: 'MyZivi Recruiting'
      .col-12.col-md-6.mt-3.mt-md-0
        .text-uppercase.text-muted.my-3 Rekrutieren
        h4 Finde rasch passende Zivis
        p
          | Erstelle ein Betriebsprofil und veröffentliche Deine Einsätze.
            Zivis finden Dich rasch und einfach. Sie bewerben sich mit einem kompletten Lebenslauf bei Dir.
            Habe stets Übersicht über Deinen Rekrutierungsprozess. Plane in wenigen Klicks einen Probetag.
        = link_to recruiting_path, class: 'btn btn-link pl-0' do
          | Mehr erfahren
          .fas.fa-angle-right.ml-2
    hr.d-md-none.my-4
    .row.mt-5
      .col-12.col-md-6.text-center.text-xl-left.order-0.order-md-1
        = vite_image_tag 'home/illustrations/administrate.svg', class: 'illustration-image', alt: 'MyZivi Admin'
      .col-12.col-md-6.mt-3.mt-md-0.order-1.order-md-0
        .text-uppercase.text-muted.my-3 Administration
        h4 Konzentration auf das, was wirklich zählt
        p
          | Plane Deine Zivi-Bedarf.
            Berechne Spesen in wenigen Klicks.
            Erstelle Telefonlisten für Deine Einsatzleiter.
            Automatisiere Deine Zahlungen.
        = link_to administration_path, class: 'btn btn-link pl-0' do
          | Mehr erfahren
          .fas.fa-angle-right.ml-2
section.advantages
  .container
    .row
      .col-12.col-md-4
        i.fas.fa-check.fa-2x.mb-3
        h4.text-white Nie mehr warten
        p Du schreibst Deine Einsätze schnell und schön aus. Zivis bewerben sich blitzschnell bei Dir und Du hast sofort alle Informationen, die Du benötigst.
      .col-12.col-md-4.mt-3.mt-md-0
        i.fas.fa-check.fa-2x.mb-3
        h4.text-white Nie mehr Zeit verlieren
        p Du automatisierst und digitalisierst  Deine Administration. Verschwende nie mehr Zeit mit Spesenauszahlungen und Einsatzvereinbarungen.
      .col-12.col-md-4.mt-3.mt-md-0
        i.fas.fa-check.fa-2x.mb-3
        h4.text-white Nie mehr Wichtiges vergessen
        p Du hast alle wichtigen Informationen überall und jederzeit zur Verfügung. Telefonlisten und ein Organisationstool lassen Dich in die Zukunft planen.

section.workflow
  .container
    h3.section-title Wie es funktioniert
    .row.mt-5
      .col-12.col-md.text-center.text-md-right
        = vite_image_tag 'home/steps/video_call.svg',
                class: 'illustration-image',
                alt: 'Einfach eine Demo vereinbaren'
      .d-none.col-md.d-md-inline-flex.justify-content-center.align-items-center.flex-grow-0
        .steps-badge 1
      .col-12.col-md.mt-3.mt-md-0
        .text-uppercase.text-muted.my-3 Demo
        h4 Interessiert? Vereinbare eine kurze Demo
        p
          | In einer kurzen Demo zeigen wir Dir, wie Du MyZivi am besten in Deinen bestehenden Prozess
            einbinden kannst.
        p
          = link_to Rails.configuration.x.urls.demo_url, rel: 'noreferrer nofollow noopener', target: '_blank' do
            span Jetzt Demo vereinbaren
            i.fas.fa-chevron-right.ml-2
    hr.d-md-none.my-4
    .row.mt-5
      .col-12.col-md.text-center.text-md-left.order-0.order-md-2
        = vite_image_tag 'home/steps/account.svg',
                class: 'illustration-image',
                alt: 'Erhalte dein Account'
      .d-none.col-md.d-md-inline-flex.justify-content-center.align-items-center.order-md-1.flex-grow-0
        .steps-badge 2
      .col-12.col-md.mt-3.mt-md-0.order-1.order-md-0
        .text-uppercase.text-muted.my-3 Account
        h4 Erhalte Deinen Account
        p
          | Sobald wir das richtige Angebot für Dich gefunden haben, wird innerhalb von einem Arbeitstag
            Dein My-Zivi-Account aufgeschaltet und Du kannst loslegen.
    hr.d-md-none.my-4
    .row.mt-5
      .col-12.col-md.text-center.text-md-right
        = vite_image_tag 'home/steps/applications.svg',
                class: 'illustration-image',
                alt: 'Erhalte Bewerbungen'
      .d-none.col-md.d-md-inline-flex.justify-content-center.align-items-center.flex-grow-0
        .steps-badge 3
      .col-12.col-md.mt-3.mt-md-0
        .text-uppercase.text-muted.my-3 Bewerbungsprozess
        h4 Erhalte Bewerbungen
        p
          | Sichte und verwalte Zivi-Bewerbungen in MyZivi und kontaktiere passende Zivis.
            Behalte den Überblick über laufende Bewerbungen mit dem praktischen Kanban-Board.
    hr.d-md-none.my-4
    .row.mt-5
      .col-12.col-md.text-center.text-md-left.order-0.order-md-2
        = vite_image_tag 'home/steps/dashboard.svg',
                class: 'illustration-image',
                alt: 'MyZivi Admin'
      .d-none.col-md.d-md-inline-flex.justify-content-center.align-items-center.order-md-1.flex-grow-0
        .steps-badge 4
      .col-12.col-md.mt-3.mt-md-0.order-1.order-md-0
        .text-uppercase.text-muted.my-3 Administration
        h4 Digitalisiere Deine Administration
        p
          | Verwalte digital Deine Spesen, Auszahlungen und Einsatzvereinbarungen.
            Mit dem Übersichts-Tool siehst Du zudem, wie viele Zivis wann im Einsatz sind.

section.py-0.quote
  .quote-container
    .container.text-center
      .container-fluid
        h3.mb-4 Interessiert?
      p.mb-2
        | Buche jetzt eine unverbindliche, kurze Demo und wir zeigen Dir, wie wir deinem Betrieb helfen können
          und vereinbaren weitere Schritte.
      p
        | Gerne kannst du uns auch unter
        a<> href="mailto:info@myzivi.ch" info@myzivi.ch
        | kontaktieren.
      .mt-4
        = link_to t('home.navbar.demo'),
                Rails.configuration.x.urls.demo_url,
                class: 'btn btn-gradient',
                target: '_blank',
                rel: 'nofollow noopener noreferrer'

section.publications
  .container.mb-2: h3.section-title MyZivi in der Presse
  .d-flex.justify-content-center.align-items-center.flex-wrap
    - %w[civia landbote salzh zhaw startupticker].each do |icon|
      .publication-icon
        = webp_picture_pack_tag("home/publications/#{icon}.webp", alt: icon.to_s.upcase_first)

section.publications.pt-0
  .container.mb-2.mt-4: h3.section-title MyZivi Partner
  .d-flex.justify-content-center.align-items-center.flex-wrap
    - %w[runway tpw gw].each do |icon|
      .publication-icon
        = webp_picture_pack_tag("home/publications/#{icon}.webp", alt: icon.to_s.upcase_first)

= render 'home/footer'

app/views/home/organizations.html.slim
- content_for(:container_class, 'index-container')
- content_for(:page_title, 'Für Betriebe')
- content_for(:displays_demo_button, true)
= render 'home/navbar'

section.solution
  .container
    h3.section-title Unsere Lösungen für Betriebe
    p.section-subtitle
      | MyZivi deckt den gesamten Prozess ab:
        Zivis finden, Bewerbungsgespräche führen, Probetage durchführen,
        einstellen, einplanen und Spesenauszahlungen vornehmen
    .row.mt-5
      .col-12.col-md-6.text-center.text-xl-right
        = image_pack_tag 'home/illustrations/recruit.svg', class: 'illustration-image', alt: 'MyZivi Recruiting'
      .col-12.col-md-6.mt-3.mt-md-0
        .text-uppercase.text-muted.my-3 Rekrutieren
        h4 Finde rasch passende Zivis
        p
          | Erstelle ein Betriebsprofil und veröffentliche Deine Einsätze.
            Zivis finden Dich rasch und einfach. Sie bewerben sich mit einem kompletten Lebenslauf bei Dir.
            Habe stets Übersicht über Deinen Rekrutierungsprozess. Plane in wenigen Klicks einen Probetag.
        = link_to recruiting_path, class: 'btn btn-link pl-0' do
          | Mehr erfahren
          .fas.fa-angle-right.ml-2
    hr.d-md-none.my-4
    .row.mt-5
      .col-12.col-md-6.text-center.text-xl-left.order-0.order-md-1
        = image_pack_tag 'home/illustrations/administrate.svg', class: 'illustration-image', alt: 'MyZivi Admin'
      .col-12.col-md-6.mt-3.mt-md-0.order-1.order-md-0
        .text-uppercase.text-muted.my-3 Administration
        h4 Konzentration auf das, was wirklich zählt
        p
          | Plane Deine Zivi-Bedarf.
            Berechne Spesen in wenigen Klicks.
            Erstelle Telefonlisten für Deine Einsatzleiter.
            Automatisiere Deine Zahlungen.
        = link_to administration_path, class: 'btn btn-link pl-0' do
          | Mehr erfahren
          .fas.fa-angle-right.ml-2
section.advantages
  .container
    .row
      .col-12.col-md-4
        i.fas.fa-check.fa-2x.mb-3
        h4.text-white Nie mehr warten
        p Du schreibst Deine Einsätze schnell und schön aus. Zivis bewerben sich blitzschnell bei Dir und Du hast sofort alle Informationen, die Du benötigst.
      .col-12.col-md-4.mt-3.mt-md-0
        i.fas.fa-check.fa-2x.mb-3
        h4.text-white Nie mehr Zeit verlieren
        p Du automatisierst und digitalisierst  Deine Administration. Verschwende nie mehr Zeit mit Spesenauszahlungen und Einsatzvereinbarungen.
      .col-12.col-md-4.mt-3.mt-md-0
        i.fas.fa-check.fa-2x.mb-3
        h4.text-white Nie mehr Wichtiges vergessen
        p Du hast alle wichtigen Informationen überall und jederzeit zur Verfügung. Telefonlisten und ein Organisationstool lassen Dich in die Zukunft planen.

section.workflow
  .container
    h3.section-title Wie es funktioniert
    .row.mt-5
      .col-12.col-md.text-center.text-md-right
        = image_pack_tag 'home/steps/video_call.svg',
                class: 'illustration-image',
                alt: 'Einfach eine Demo vereinbaren'
      .d-none.col-md.d-md-inline-flex.justify-content-center.align-items-center.flex-grow-0
        .steps-badge 1
      .col-12.col-md.mt-3.mt-md-0
        .text-uppercase.text-muted.my-3 Demo
        h4 Interessiert? Vereinbare eine kurze Demo
        p
          | In einer kurzen Demo zeigen wir Dir, wie Du MyZivi am besten in Deinen bestehenden Prozess
            einbinden kannst.
        p
          = link_to ENV['DEMO_URL'], rel: 'noreferrer nofollow noopener', target: '_blank' do
            span Jetzt Demo vereinbaren
            i.fas.fa-chevron-right.ml-2
    hr.d-md-none.my-4
    .row.mt-5
      .col-12.col-md.text-center.text-md-left.order-0.order-md-2
        = image_pack_tag 'home/steps/account.svg',
                class: 'illustration-image',
                alt: 'Erhalte dein Account'
      .d-none.col-md.d-md-inline-flex.justify-content-center.align-items-center.order-md-1.flex-grow-0
        .steps-badge 2
      .col-12.col-md.mt-3.mt-md-0.order-1.order-md-0
        .text-uppercase.text-muted.my-3 Account
        h4 Erhalte Deinen Account
        p
          | Sobald wir das richtige Angebot für Dich gefunden haben, wird innerhalb von einem Arbeitstag
            Dein My-Zivi-Account aufgeschaltet und Du kannst loslegen.
    hr.d-md-none.my-4
    .row.mt-5
      .col-12.col-md.text-center.text-md-right
        = image_pack_tag 'home/steps/applications.svg',
                class: 'illustration-image',
                alt: 'Erhalte Bewerbungen'
      .d-none.col-md.d-md-inline-flex.justify-content-center.align-items-center.flex-grow-0
        .steps-badge 3
      .col-12.col-md.mt-3.mt-md-0
        .text-uppercase.text-muted.my-3 Bewerbungsprozess
        h4 Erhalte Bewerbungen
        p
          | Sichte und verwalte Zivi-Bewerbungen in MyZivi und kontaktiere passende Zivis.
            Behalte den Überblick über laufende Bewerbungen mit dem praktischen Kanban-Board.
    hr.d-md-none.my-4
    .row.mt-5
      .col-12.col-md.text-center.text-md-left.order-0.order-md-2
        = image_pack_tag 'home/steps/dashboard.svg',
                class: 'illustration-image',
                alt: 'MyZivi Admin'
      .d-none.col-md.d-md-inline-flex.justify-content-center.align-items-center.order-md-1.flex-grow-0
        .steps-badge 4
      .col-12.col-md.mt-3.mt-md-0.order-1.order-md-0
        .text-uppercase.text-muted.my-3 Administration
        h4 Digitalisiere Deine Administration
        p
          | Verwalte digital Deine Spesen, Auszahlungen und Einsatzvereinbarungen.
            Mit dem Übersichts-Tool siehst Du zudem, wie viele Zivis wann im Einsatz sind.

section.py-0.quote
  .quote-container
    .container.text-center
      .container-fluid
        h3.mb-4 Interessiert?
      p.mb-2
        | Buche jetzt eine unverbindliche, kurze Demo und wir zeigen Dir, wie wir deinem Betrieb helfen können
          und vereinbaren weitere Schritte.
      p
        | Gerne kannst du uns auch unter
        a<> href="mailto:info@myzivi.ch" info@myzivi.ch
        | kontaktieren.
      .mt-4
        = link_to t('home.navbar.demo'),
                ENV['DEMO_URL'],
                class: 'btn btn-gradient',
                target: '_blank',
                rel: 'nofollow noopener noreferrer'

section.publications
  .container.mb-2: h3.section-title MyZivi in der Presse
  .d-flex.justify-content-center.align-items-center.flex-wrap
    - %w[civia landbote salzh zhaw startupticker].each do |icon|
      .publication-icon
        = webp_picture_pack_tag("home/publications/#{icon}.webp", alt: icon.to_s.upcase_first)

section.publications.pt-0
  .container.mb-2.mt-4: h3.section-title MyZivi Partner
  .d-flex.justify-content-center.align-items-center.flex-wrap
    - %w[runway tpw gw].each do |icon|
      .publication-icon
        = webp_picture_pack_tag("home/publications/#{icon}.webp", alt: icon.to_s.upcase_first)

= render 'home/footer'